---

- name: Copy spring-petclinic to guest
  copy:
    src: "~/spring-petclinic/target/spring-petclinic-{{appversion}}.jar"
    dest: ~/

- name: Copy nginx config
  become: true
  copy:
    src: spring-petclinic.conf
    dest: /etc/nginx/sites-enabled/spring.conf

- name: Create service
  become: true
  template:
    src: service.j2
    dest: /etc/systemd/system/spring-petclinic.service
